### ISSUE TITLE
Model gets stuck (or extremely slow) after processing around 22,000 pupils

### ISSUE THREAD

**Issue by MarkLTurner** [DurhamARC/classroom-abm#100]

**Comment by MarkLTurner** [comment]
Initially this was identified when running with 24 cores on Hamilton's par7.q. First step was to test whether reducing the number of cores helped us here (I wondered whether the network gets highly congested and deadlocks somehow). At the moment we offload responsibility for parallelisation to Mesa's batchrunner - the hypothesis was that this was not up to the task of scaling to 24 cores on Hamilton.

However, we see the same issue with 16 and 8 cores (although it seems to happen slightly later - i.e. the slow down happens after a further 2000 or so pupils have been processed).

**Comment by MarkLTurner** [comment]
I am waiting on my Hamilton jobs to get time on par7.q. On my local machine I notice, however, that the model begins very quickly and then suddenly begins to slow. This is evident in webserver mode if you move 'Frames Per Second' to 0 (a hack for making the model run at full speed). I am currently placing timers to pin point what is responsible for this. My initial data suggests that it is not the step function that is responsible - even after 1000 steps the time per step is still under 0.0006 (up from 0.0001).

**Comment by alisonrclarke** [comment]
I'll try adding some logging to see if that helps us see where it's getting stuck.

**Comment by MarkLTurner** [comment]
Update: memory issues were discovered. When we run with the batchrunner on Hamilton with the big dataset the memory footprint of one process (out of 24) grows continuously until we overwhelm the node we are working on. None of the other processes increase beyond 1% of the nodes memory.

Removing agent reporters from the batchrunner has been tested and made no difference.

Next we will try
1. Preventing collection of data per step when not in webserver mode.
2. OutputDataWriter should only write and not save data.

**Comment by alisonrclarke** [comment]
Also realised that the `TruncatedNormalGenerator` class was having to be pickled by `BatchRunner`, suggesting that `BatchRunner` was keeping a reference to it and all its random values. Now trying removing the model classes `TruncatedNormalGenerator` instances at the end of a run.

**Comment by alisonrclarke** [comment]
Have opened #105 to deal with issues in webserver mode.
