### ISSUE TITLE
Reset pupils to amber state on a weekly

### ISSUE THREAD

**Issue by MarkLTurner** [DurhamARC/classroom-abm#101]
We have discussed whether pupils should be reset to an amber state at regular intervals. We considered resetting on a daily or weekly basis and decided to go with the latter. It seems that is what is supposed to happen [here](https://github.com/DurhamARC/classroom-abm/blob/master/MesaModel/model/SimModel.py#L284), though it is not working.

**Comment by alisonrclarke** [comment]
I've just checked by adding a breakpoint and it appears to be working OK.

**Comment by MarkLTurner** [comment]
Closing as I didn't realise the number of steps per day now vary.
