### ISSUE TITLE
Work out why using ANDs not ORs has stopped states changing

### ISSUE THREAD

**Issue by alisonrclarke** [DurhamARC/classroom-abm#75]
The NetLogo model was modified in f155a3a to replace ANDs with ORs. Following our discussion with Peter and Chris I've changed it back on the logic-updates branch, but it greatly decreases the chances of state updates (which is why it was changed previously). We all agree that logically we should be using ANDs, so we should go back through the history (probably of the NetLogo model) to work out why ANDs aren't working as we expect and at what point we started seeing issues.

**Comment by alisonrclarke** [comment]
It may be more apparent what's going on once we remove the home learning steps from the visualisation in #60.

**Comment by alisonrclarke** [comment]
Peter says:

> It seems that once a pupil is disruptive he/she stays disruptive. It should not be like that.
> A similar thing happens with learning students and this results in the whole class learning and stuck in that state.

Couple of suggestions:

1. Reduce the number of neighbours needed to change the state from red or green to yellow, depending on group size. (Currently it's fixed at 2 but we should do something similar to `self.min_neighbour_count_to_modify_state` for the smaller values as well - see 30feaa78)
2. Consider resetting pupils at the start of each day instead of each week.

**Comment by alisonrclarke** [comment]
Realised what's going on here. When the ANDs were changed to ORs in the NetLogo model in f155a3a, I'd assumed that all ORs had previously been ANDs, but that wasn't the case, e.g. in lines 339/344 and 376/384 in that commit, the conditions for changing from Red/Green back to Yellow were previously ORs, so there are 2 different possibilities for getting out of the red/green states.
When updating the logic in 664c367 I assumed they'd all previously been ANDs so changed them all. Mea culpa.

**Comment by PeterTymms** [comment]
This sounds like an important find

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
